### ISSUE TITLE
VA332 - Create new car in catalogue

### ISSUE THREAD

**Issue by lfvm** [IvanDLar/MOVU-Docs#104]
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/173
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/174
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/175
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/176
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/199

**Comment by marriagav** [comment]
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/173
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/174
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/175
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/176
