### ISSUE TITLE
VA334 - Remove car from catalogue

### ISSUE THREAD

**Issue by lfvm** [IvanDLar/MOVU-Docs#107]
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/173
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/174
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/175
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/199

**Comment by marriagav** [comment]
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/173
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/174
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/175
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/176
