### ISSUE TITLE
VA061 - Table with all the applications of the automotive groups.

### ISSUE THREAD

**Issue by AnYelg** [IvanDLar/MOVU-Docs#111]
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/79
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/139
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/154

**Comment by marcotorresx** [comment]
- [ ] https://github.com/IvanDLar/MOVU-FrontEnd/issues/139
