### ISSUE TITLE
VA401 - The landing page will have a search bar where the users will be able to write a simple car description which will then return a list of vehicles that match that criteria.

### ISSUE THREAD

**Issue by lfvm** [IvanDLar/MOVU-Docs#124]
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/54
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/58
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/83

**Comment by IvanDLar** [comment]
Please discuss this tasks and the state of this validation @marcotorresx  and @MiguelBusta .
