### ISSUE TITLE
VA075 - If at least one field is not valid, the automotive group administrator can not continue registering.

### ISSUE THREAD

**Issue by AnYelg** [IvanDLar/MOVU-Docs#132]
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/171
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/172

**Comment by marriagav** [comment]
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/171
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/172
