### ISSUE TITLE
VA076 - The automotive group administrator lands on the application page where they can submit their documents and wait for the super admin to validate.

### ISSUE THREAD

**Issue by AnYelg** [IvanDLar/MOVU-Docs#133]
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/139
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/171
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/172

**Comment by marcotorresx** [comment]
- [ ] https://github.com/IvanDLar/MOVU-FrontEnd/issues/139

**Comment by marriagav** [comment]
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/171
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/172
