### ISSUE TITLE
VA078 - When the status of application is accepted the car dealership can access the automotive group administrator web page sections.

### ISSUE THREAD

**Issue by AnYelg** [IvanDLar/MOVU-Docs#135]
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/171
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/172

**Comment by marriagav** [comment]
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/171
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/172
