### ISSUE TITLE
VA081 - Form where managers can register seller from their agency.

### ISSUE THREAD

**Issue by AnYelg** [IvanDLar/MOVU-Docs#136]
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/198
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/170

**Comment by marriagav** [comment]
- [ ] https://github.com/IvanDLar/MOVU-FrontEnd/issues/198
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/170
