### ISSUE TITLE
VA161 - When a manager uploads a car, he will need to fill out a cost section where he can add fixed options that his car dealership has available, such as the different insurance plans, and financing options so that platform users can view them in their quotes.

### ISSUE THREAD

**Issue by IvanDLar** [IvanDLar/MOVU-Docs#159]
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/173
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/174
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/175
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/176
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/199

**Comment by marriagav** [comment]
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/173
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/174
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/175
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/176
