### ISSUE TITLE
VA162 -  A submit button that will upload to the cars page the financing  and insurance options.

### ISSUE THREAD

**Issue by IvanDLar** [IvanDLar/MOVU-Docs#160]
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/176
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/263

**Comment by marriagav** [comment]
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/176
