### ISSUE TITLE
VA171 - Form where automotive group manager can input the necessary information in order to submit the car dealership application.

### ISSUE THREAD

**Issue by IvanDLar** [IvanDLar/MOVU-Docs#162]
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/171
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/172
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/205

**Comment by marriagav** [comment]
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/171
- [ ] https://github.com/IvanDLar/MOVU-BackEnd/issues/172
