### ISSUE TITLE
VA172 - The automotive group administrator lands on the application page where they can submit the documents to register the car dealership and wait for the super admin to validate.

### ISSUE THREAD

**Issue by IvanDLar** [IvanDLar/MOVU-Docs#163]
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/139
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/171
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/172

**Comment by marcotorresx** [comment]
- [ ] https://github.com/IvanDLar/MOVU-FrontEnd/issues/139
