### ISSUE TITLE
- VA181 Reflect changes on the final price when selecting extras, such as car customizations and financing/insurance options. 

### ISSUE THREAD

**Issue by IvanDLar** [IvanDLar/MOVU-Docs#166]

**Comment by u-urieldev** [comment]
Esto es de checkout y no se si se haga

**Comment by IvanDLar** [comment]
No creo que se pueda hacer con el tiempo que tenemos, la cerraré por el momento

**Comment by IvanDLar** [comment]
Out of scope due to time constraints, we overestimated the team effort against the time we had available.
