### ISSUE TITLE
VA251 - Each user will have their corresponding roles assigned that will grant them specific actions

### ISSUE THREAD

**Issue by SalomonDabs** [IvanDLar/MOVU-Docs#219]
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/143
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/173
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/172
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/197

**Comment by marcotorresx** [comment]
- [ ] https://github.com/IvanDLar/MOVU-FrontEnd/issues/143
