### ISSUE TITLE
Testing Document Normalization

### ISSUE THREAD

**Issue by IvanDLar** [IvanDLar/MOVU-Docs#6]
### Sub Tasks
- [x] Create a folder with the test templates (the test reports will be placed there)
- [x] Attach test diagram to document
- [x] Define the environment in which the tests will be carried out (local and cloud)
- [x] Define the tools that will be used to develop the tests
- [x] Definition of roles table.
- [x] Definition of test environment for E2E and Integration tests, and tools to be used in the pipeline.
- [x] Definition of itinerary of activities.

**Comment by marriagav** [comment]
Document: https://github.com/IvanDLar/MOVU-Docs/blob/main/wiki/Test%20Plan.md
Tasks completed:
- Create a folder with the test templates (the test reports will be placed there)
- Attach test diagram to document
- Define the environment in which the tests will be carried out (local and cloud)
- Define the tools that will be used to develop the tests
- Definition of roles table.
- Definition of test environment for E2E and Integration tests, and tools to be used in the pipeline.
- Definition of itinerary of activities.
