### ISSUE TITLE
VA552 Once the user answers a form with specific information as well add sending its valid driver license, he will have to wait for the agencies approval

### ISSUE THREAD

**Issue by SalomonDabs** [IvanDLar/MOVU-Docs#66]
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/94
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/96
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/97
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/103
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/104
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/244
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/284
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/310
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/356

**Comment by AnYelg** [comment]
- [ ] https://github.com/IvanDLar/MOVU-FrontEnd/issues/94
- [ ] https://github.com/IvanDLar/MOVU-FrontEnd/issues/96

- [ ] [ ]
