### ISSUE TITLE
VA561 - Salesman Dashboard will be a section to manage the test drives. Here the salesman can view the applications as well as approving or denying the test

### ISSUE THREAD

**Issue by SalomonDabs** [IvanDLar/MOVU-Docs#86]
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/100
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/293
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/102
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/292
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/99
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/285
- [x] https://github.com/IvanDLar/MOVU-FrontEnd/issues/330
- [x] https://github.com/IvanDLar/MOVU-BackEnd/issues/94

**Comment by AnYelg** [comment]
- [ ] https://github.com/IvanDLar/MOVU-FrontEnd/issues/100
- [ ] https://github.com/IvanDLar/MOVU-FrontEnd/issues/101
